// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Generated by `flutterfire configure` for project talkk-voice-app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwfnL5lSu9Lybf89n6PhV80gh5sNxbI4',
    appId: '1:29312418322:android:4c3348e40f409115ad4ecb',
    messagingSenderId: '29312418322',
    projectId: 'talkk-voice-app',
    storageBucket: 'talkk-voice-app.firebasestorage.app',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3mL1lclD2rlJHRgevRMKP6VwQ708Z7A',
    appId: '1:29312418322:ios:83da41f6902b6cbfad4ecb',
    messagingSenderId: '29312418322',
    projectId: 'talkk-voice-app',
    storageBucket: 'talkk-voice-app.firebasestorage.app',
    iosBundleId: 'com.talkk.talkFlutter',
  );


}